### PR TITLE
fix: lang string issues on step creation

### LINKED ISSUE #556: Lang string issues on step creation
```
Invalid $a identifier for string helper must be a string identifier.

    line 275 of /admin/tool/dataflows/classes/form/step_form.php: call to renderer_base->render_from_template()
    line 99 of /admin/tool/dataflows/classes/form/step_form.php: call to tool_dataflows\form\step_form->prepare_available_fields()
    line 255 of /lib/formslib.php: call to tool_dataflows\form\step_form->definition()
    line 110 of /lib/classes/form/persistent.php: call to moodleform->__construct()
    line 87 of /admin/tool/dataflows/step.php: call to core\form\persistent->__construct()
```

Tested on T16

Steps:
1 - Create new dataflow
2 - Visit this page to add a new step type and see the warning `/admin/tool/dataflows/step.php?dataflowid=1&type=tool_dataflows\local\step\connector_curl`

### PR DESCRIPTION
**Pull request by keevan**
Mustache might work different in Totara, but pulling this back into PHP-land and preparing the contents there seems to have helped

Resolves #556

### CODE REVIEW

File: classes/form/step_form.php [hunk 1]
```diff
@@ -272,7 +272,10 @@ private function prepare_available_fields($variables): string {
         // Annoyingly, will need to reconvert this into an array so it can be looped over in mustache.
         $allfields = $this->build_treetag($fields);
         $allfields = $this->add_recursive_keys($fields, $allfields);
-        $fieldhtml = $OUTPUT->render_from_template('tool_dataflows/available-fields', ['groups' => $allfields]);
+        $fieldhtml = $OUTPUT->render_from_template('tool_dataflows/available-fields', [
+            'groups' => $allfields,
+            'help' => get_string('available_fields_help', 'tool_dataflows', '<code>${{ dataflow.name }}</code>'),
```
Comment (Peterburnett) [inline classes/form/step_form.php:277]: This seems to have lost the empty span. Shouldnt do anything, do you know why that was there?

Comment (keevan) [reply classes/form/step_form.php:277]: AFAIK the empty span was a hackaround to get the `${{ }}` to NOT evaluate in mustache.

Comment (Peterburnett) [reply classes/form/step_form.php:277]: christ.
