### PR TITLE
fix: add updated privacy api implementation based on current db fields

### LINKED ISSUE #56: Add/Implement privacy classes
Based on CI run
```
 There was 1 failure:

1) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - tool_dataflows (userid)
  - tool_dataflows_steps (userid)

/home/runner/work/moodle-tool_dataflows/moodle-tool_dataflows/moodle/privacy/tests/provider_test.php:311
/home/runner/work/moodle-tool_dataflows/moodle-tool_dataflows/moodle/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///home/runner/work/moodle-tool_dataflows/moodle-tool_dataflows/moodle/vendor/phpunit/phpunit/phpunit:52

To re-run:
 vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php
```

### PR DESCRIPTION
**Pull request by keevan**
This should resolve CI issues.

Resolves #56

### CODE REVIEW

File: classes/privacy/provider.php [hunk 1]
```diff
@@ -16,23 +16,231 @@
...
+        $userid = $contextlist->get_user()->id;
+        foreach ($contextlist as $context) {
+            if ($context->contextlevel == CONTEXT_SYSTEM) {
+                self::delete_data_by_userid($userid);
+            }
+        }
+    }
+
+    /**
+     * Description of what this does
```
Comment (jaypha) [inline classes/privacy/provider.php:170]: Best description ever!

Comment (keevan) [reply classes/privacy/provider.php:170]: Ah the classic placeholder comment that makes it seem it has been filled out (when glancing).

Nice catch @jaypha, I'll fix this up :)
