### PR TITLE
Issue #756: Refactor has_side_effect() to evaluate expressions.

### LINKED ISSUE #756: Side effect checks fail when filenames contain expressions.
For example remove_file_trait::has_side_effect() returns incorrectly, if the filename is '${{dataflow.vars.somedir}}/somefile'.

Steps that need to be updated:
- [x] remove_file
- [x] gpg
- [x] append_file
- [x] s3
- [x] sftp

Update unit tests
- [x] remove_file
- [ ] gpg
- [x] append_file
- [ ] s3
- [ ] sftp

### PR DESCRIPTION
**Pull request by jaypha**
Resolves #756

### CODE REVIEW

File: tests/tool_dataflows_connector_s3_test.php [hunk 1]
```diff
@@ -231,49 +231,73 @@ public function test_validate_for_run_extra() {
...
         $dataflow = new dataflow();
         $dataflow->name = 'dataflow';
         $dataflow->enabled = true;
         $dataflow->save();
 
-        // Test both source and target being outside of scratch dir.
         $step = new step();
         $step->name = 'somename';
-        $step->type = 'tool_dataflows\local\step\connector_s3';
+        $step->type = connector_s3::class;;
```
Comment (keevan) [inline tests/tool_dataflows_connector_s3_test.php:280]: Double semi here.
```suggestion
        $step->type = connector_s3::class;
```

**Review by keevan — APPROVED** [review]
Looks good otherwise :)
