### PR TITLE
Issue 142: Fix helper::path_is_relative() and helper::path_validate() to expand [dataroot] placeholder before testing.

### LINKED ISSUE #701: Helper methods fail to expand [dataroot] before performing checks.
Both helper::path_validate() and helper::path_is_relative() fail to expand [dataroot] before performing their checks.

### PR DESCRIPTION
**Pull request by jaypha**
Resolves #701

### CODE REVIEW

File: tests/tool_dataflows_helper_test.php [hunk 1]
```diff
@@ -34,6 +34,35 @@ protected function setUp(): void {
...
+     */
+    public function is_relative_provider(): array {
+        global $CFG;
+        return [
+            ['one/path', true],
+            ['/one/path', false],
+            ['file://one/path', false],
+            ['sftp://one/path', false],
+            ['sftp/files/download.txt', true],
+            ['[dataroot]/stuff/one/path', strpos($CFG->dataroot, '/') !== 0],
```
Comment (brendanheywood) [inline tests/tool_dataflows_helper_test.php:62]: it is not ideal to have logic inside a data provider, shouldn't this one always return false as it will never be relative?

Comment (jaypha) [reply tests/tool_dataflows_helper_test.php]: fixed
