### PR TITLE
Issue #372: Fix step alias validation

### LINKED ISSUE #372: step alias should not allow thing containing a .
eg `send_mdl_quiz.json_to_s3`

This could easily be ambogous if there was another step with an alias of `send_mdl_quiz`

### PR DESCRIPTION
**Pull request by jaypha**
Resolves #372

Add rule to alias element in step_form.
Add validate_alias() method to step.
Add unit tests.

### CODE REVIEW

File: classes/form/step_form.php [hunk 1]
```diff
@@ -70,6 +71,7 @@ public function definition() {
         // Alias for the step (e.g. id-like field of a yaml configured dataflow, if absent, the key for the step).
         $mform->addElement('text', 'alias', get_string('field_alias', 'tool_dataflows'));
         $mform->addElement('static', 'alias_help', '', get_string('field_alias_help', 'tool_dataflows'));
+        $mform->addRule('alias', get_string('invalid_value', 'tool_dataflows'), 'regex', step::ALIAS_REGEX, 'client');
```
Comment (brendanheywood) [inline classes/form/step_form.php:74]: why not just PARAM_ALPHANUMEXT ?

Comment (jaypha) [reply classes/form/step_form.php:74]: Unfortunately, there are no defined constants for the regexes for PARAM_*. I changed the regex to be compatible with PARAM_ALPHANUMEXT, but I still have to provide it myself.
