### PR TITLE
277 phpcs fixes

### LINKED ISSUE #277: Clean up phpcs warnings in codebase.

### PR DESCRIPTION
**Pull request by keevan**
- style: fix phpcs issues
- style: phpcs fix warnings regarding line length

Resolves  #277

### CODE REVIEW

File: db/tasks.php [hunk 1]
```diff
@@ -25,14 +25,14 @@
...
-    array(
+$tasks = [
+    [
         'classname' => 'tool_dataflows\task\process_dataflows',
         'blocking' => 0,
         'minute' => '*',
         'hour' => '*',
         'day' => '*',
         'dayofweek' => '*',
         'month' => '*'
```
Comment (jaypha) [inline db/tasks.php:36]: This needs a comma.

Comment (keevan) [reply db/tasks.php]: Added
