### PR TITLE
Issue #102: Fix dataflow run error

### LINKED ISSUE #102: Notice:  Trying to get property 'iterator' of non-object in ...dataflows/classes/step/flow_step.php on line 74
Rename to yml to upload and test

[data_20220525_0640.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/8768660/data_20220525_0640.yml.txt)

Encountered this when trying to run a test flow. Might be a type coercion gone wrong.

```
    Stack trace:  

    line 39 of /admin/tool/dataflows/classes/execution/iterators/map_iterator.php: TypeError thrown
    line 75 of /admin/tool/dataflows/classes/step/flow_step.php: call to tool_dataflows\execution\iterators\map_iterator->__construct()
    line 62 of /admin/tool/dataflows/classes/execution/flow_engine_step.php: call to tool_dataflows\step\flow_step->get_iterator()
    line 173 of /admin/tool/dataflows/classes/execution/engine.php: call to tool_dataflows\execution\flow_engine_step->go()
    line 151 of /admin/tool/dataflows/classes/execution/engine.php: call to tool_dataflows\execution\engine->execute_step()
    line 99 of /admin/tool/dataflows/run.php: call to tool_dataflows\execution\engine->execute()
```

### PR DESCRIPTION
**Pull request by jaypha**
Resolves #102 
Make 1 inputstream the default min requirement for flow steps.
Add check that mapping steps have at least 1 input.
Add inputstream restriction to array_in_type.
Change use of debugging steptypes to array_in in unit tests.

OK to squash.

### CODE REVIEW

File: classes/step/flow_step.php [hunk 1]
```diff
@@ -32,6 +32,10 @@
  */
 abstract class flow_step extends base_step {
 
+    /** @var int[] number of input streams (min, max) */
+    // Flow steps default to min 1 input.
```
Comment (keevan) [inline classes/step/flow_step.php:36]: It seems  this comment can be better formatted, preferably all under the `/* ... */`

File: tests/tool_dataflows_test.php [hunk 2]
```diff
@@ -23,6 +23,7 @@
 
 // Include lib.php functions that aren't included automatically for Moodle 37- and below.
 require_once(dirname(__FILE__) . '/../lib.php');
+require_once(__DIR__ . "/execution/array_in_type.php"); // This is needed. File will not be automatically included.
```
Comment (keevan) [inline tests/tool_dataflows_test.php:26]: Should be single quotes, and are you able to make this consistent for both includes please.
