### PR TITLE
fix: step to be extended from flow_step to correct output links

### LINKED ISSUE #418: Web service not extending from correct class
Results in numbered / labelled outputs when it should just be 1-1

### PR DESCRIPTION
**Pull request by keevan**
Resolves #418

### CODE REVIEW

File: classes/local/step/flow_web_service.php [hunk 1]
```diff
@@ -29,7 +29,7 @@
  * @copyright  Catalyst IT, 2022
  * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
  */
-class flow_web_service extends flow_logic_step {
+class flow_web_service extends flow_step {
```
Comment (brendanheywood) [inline classes/local/step/flow_web_service.php:32]: This makes the step disappear completely from the chooser? purged caches and still no dice

Comment (brendanheywood) [reply classes/local/step/flow_web_service.php:32]: made https://github.com/catalyst/moodle-tool_dataflows/issues/425
