### PR TITLE
fix t16 unit tests

### LINKED ISSUE #549: Failing unit tests (web request related) on Totara 16
From a glance this is most likely due to flaky HTTP requests that aren't guaranteed to be available?

```
........E......................................................  63 / 135 ( 46%)
...........................................S...........E....... 126 / 135 ( 93%)
......E..                                                       135 / 135 (100%)

Time: 00:16.082, Memory: 514.70 MB

There were 3 errors:

1) tool_dataflows\tool_dataflows_connector_curl_test::test_execute
moodle_exception: 404:&lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
&lt;html&gt;&lt;head&gt;
&lt;title&gt;404 Not Found&lt;/title&gt;
&lt;/head&gt;&lt;body&gt;
&lt;h1&gt;Not Found&lt;/h1&gt;
&lt;p&gt;The requested URL /exttests/h5puuid.json was not found on this server.&lt;/p&gt;
&lt;/body&gt;&lt;/html&gt;


/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/step/connector_curl.php:293
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/connector_engine_step.php:47
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/engine.php:426
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/engine.php:381
/var/www/mysite-totara/server/admin/tool/dataflows/tests/tool_dataflows_connector_curl_test.php:76
/var/www/mysite-totara/server/lib/phpunit/classes/testcase.php:114

2) tool_dataflows\tool_dataflows_variables_test::test_output_variables
moodle_exception: 404:&lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
&lt;html&gt;&lt;head&gt;
&lt;title&gt;404 Not Found&lt;/title&gt;
&lt;/head&gt;&lt;body&gt;
&lt;h1&gt;Not Found&lt;/h1&gt;
&lt;p&gt;The requested URL /exttests/h5pcontenttypes.json was not found on this server.&lt;/p&gt;
&lt;/body&gt;&lt;/html&gt;


/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/step/connector_curl.php:293
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/connector_engine_step.php:47
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/engine.php:426
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/engine.php:381
/var/www/mysite-totara/server/admin/tool/dataflows/tests/tool_dataflows_variables_test.php:317
/var/www/mysite-totara/server/lib/phpunit/classes/testcase.php:114

3) tool_dataflows\tool_dataflows_web_service_flow_test::test_execute
moodle_exception: 404:1

/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/step/connector_curl.php:293
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/connector_engine_step.php:47
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/engine.php:426
/var/www/mysite-totara/server/admin/tool/dataflows/classes/local/execution/engine.php:381
/var/www/mysite-totara/server/admin/tool/dataflows/tests/tool_dataflows_web_service_flow_test.php:124
/var/www/mysite-totara/server/lib/phpunit/classes/testcase.php:114

ERRORS!
Tests: 135, Assertions: 339, Errors: 3, Skipped: 1.
```

### PR DESCRIPTION
**Pull request by keevan**
- feat: allow curl step to use alternative curl class
- fix: web request unit tests for t16+

Resolves #549

### CODE REVIEW

File: classes/local/step/connector_curl.php [hunk 1]
```diff
@@ -289,7 +289,7 @@ public function execute(): bool {
         $destination = !empty($config->destination) ? $config->destination : null;
         $errno = $curl->get_errno();
 
-        if (($httpcode >= self::HTTP_ERROR || empty($response) || $errno == CURLE_OPERATION_TIMEDOUT)) {
+        if (($httpcode >= self::HTTP_ERROR || $errno == CURLE_OPERATION_TIMEDOUT)) {
```
Comment (Peterburnett) [inline classes/local/step/connector_curl.php:292]: Why do we want to allow empty responses here? Surely we should always get atleast some headers?

Comment (Peterburnett) [reply classes/local/step/connector_curl.php:292]: NVM PUT has an empty response body, and other stuff will be in a different curl field. blame monday mornings
