### PR TITLE
More helpful debugging

### LINKED ISSUE #723: SQL flow step doesn't expose the exception message for DML exceptions
The message contains the DB message, eg relation does not exist, so it should be thrown back out

### PR DESCRIPTION
**Pull request by Peterburnett**
image
Closes #723

### CODE REVIEW

**Review by brendanheywood — APPROVED** [review]

File: classes/local/execution/engine.php [hunk 1]
```diff
@@ -508,6 +508,7 @@ public function finalise() {
     public function abort(?\Throwable $reason = null) {
         if (isset($reason)) {
             $message = $reason->getMessage();
+            $message .= PHP_EOL . $reason->debuginfo;
```
Comment (keevan) [inline classes/local/execution/engine.php:511]: Would this be better?
```suggestion
            $message = $reason->getMessage() . PHP_EOL . $reason->debuginfo;
```
