### PR TITLE
Issue 683: Fix clear_dependent() to correctly remove dependents.

### LINKED ISSUE #683: PHP8.0 - deprecated
Deprecated: array_udiff(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /var/www/html/admin/tool/dataflows/classes/local/variables/var_value.php on line 172

### PR DESCRIPTION
**Pull request by jaypha**
Resolves #683

### CODE REVIEW

File: classes/local/variables/var_value.php [hunk 1]
```diff
@@ -164,13 +164,12 @@ public function evaluate(?callable $errorhandler = null) {
...
-            [$var],
-            function ($a, $b) {
-                return $a === $b;
+        foreach ($this->dependents as $idx => $dep) {
+            if ($dep === $var) {
+                unset($this->dependents[$idx]);
+                return;
             }
-        );
+        }
```
Comment (keevan) [inline classes/local/variables/var_value.php:172]: This change does make it easier to understand what's happening, personally I was not really familiar with array_udiff. 

Instead of having a loop, would using `array_search` make more sense here? For example:
```
$idx = array_search($var, $this->dependents, true);
unset($this->dependents[$idx]);
```

**Review by keevan — COMMENTED** [review]
One small comment, the rest looks okay to me.

File: classes/local/variables/var_value.php (hunk 1 above)
Comment (jaypha) [reply classes/local/variables/var_value.php:172]: array_udiff does not appear to work if the array elements do not have a defined order. If I use 0 for same, 1 for not same, it will fail.

Comment (jaypha) [reply classes/local/variables/var_value.php:172]: Thanks for the tip. I've been working with PHP for almost 20 years now, and there is still so much I don't know.

Comment (jaypha) [reply classes/local/variables/var_value.php]: Done

**Review by keevan — APPROVED** [review]
