### PR TITLE
[#797] fix: sql flow step to switch cases in case insensitive manner

### LINKED ISSUE #797: SQL flow step match not working for different cases
https://github.com/catalyst/moodle-tool_dataflows/blob/09b7d2f8c0c2b307febf97251fa5b96e5b8e4933/classes/local/step/flow_sql.php#L81-L88

Here the check is case insensitive but the switch-case statement assumes a particular case (upper), this is causing dropped results from SQL queries which do not have the proper casing.

### PR DESCRIPTION
**Pull request by keevan**
Closes #797

### CODE REVIEW

File: classes/local/step/flow_sql.php [hunk 1]
```diff
@@ -85,7 +85,7 @@ public function execute($input = null) {
         // Matches[0] contains the match. Fallthrough to default on no match.
         $token = $matches[0] ?? '';
 
-        switch($token) {
+        switch(strtoupper($token)) {
```
Comment (keevan) [inline classes/local/step/flow_sql.php:88]: Potentially could transform the case to upper in a prior line. Might be cleaner to read. Let me know anyways :)

**Review by Peterburnett — APPROVED** [review]
