### PR TITLE
fix(s3): adjust input requirements, output constraints, improve logging

### LINKED ISSUE #597: Add s3 copy in a flow step

### PR DESCRIPTION
**Pull request by keevan**
Resolves #597

### CODE REVIEW

File: classes/local/step/flow_s3.php [hunk 1]
```diff
@@ -0,0 +1,305 @@
...
+/**
+ * S3 flow step
+ *
+ * @package    tool_dataflows
+ * @author     Peter Burnettt <peterburnett@catalyst-au.net>
+ * @author     Kevin Pham <kevinpham@catalyst-au.net>
+ * @copyright  Catalyst IT, 2022
+ * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
+ */
+class flow_s3 extends flow_step {
```
Comment (Peterburnett) [inline classes/local/step/flow_s3.php:30]: See comments from #588, it looks like this PR was accidentally included in that one.
